### ISSUE TITLE
Listen To Documents

### ISSUE THREAD

**Issue by willsower** [hutchresearch/latex2speech#104]
All documents are currently stored in `\Documentation\Listen` that currenty pass the TexParser & Pass through Polly perfectly fine. I will write the name of the .tex files below that are currently available in `\Listen` directory. You will need to run the file through your local environment to get the audio link.

File 1: gameon.tex

File 2: gameparadox-v7.tex

File 3: halo.tex

File 4: Conditions_for_monopolies.tex

File 5: LanconMoucine.tex

File 6: fennel.tex 

File 7: woottena.tex

File 8: seedingthermal.tex (math heavy) -> Listening to this, super fast o.O

File 9: paper-aas.tex

File 10: Crockett_area.tex

File 11: Mourachkine.tex (Only has 2 mathmode did not render)

File 12: paper2_astroph.tex

File 13: cascade_EPL.tex

File 14: stripes_4.tex

**Comment by willsower** [comment]
# Gameon.tex
## Notes:
When reading the author, they use $ $ to add asterisks (which isn’t mathmode really).
They also have accents which our parser doesn’t render
When our parser runs across `\emph{words here}.` with a period after the emphasis, it says “dot”
For \cite commands, maybe change “Cite as” instead of what is currently said “Cited in reference as”
The way we are currently doing the “item” command, doesn’t render mathmdoe or inner commands/env
\ref{} needs to be relooked at along with labels (expand_labels)

## Tags Not Read:
\kewords{}
\abstract {}
\ldots{}

**Comment by willsower** [comment]
# Fennel.tex
## Notes:
- It totally skipped most of \author??
- Should we say abstract when \begin{abstract}
- Mathmode here is awful, but they use mathmode for subscripts like `T$_v$`

## Tags Not Read:
\journalname{}
\offprints{}
\institute{}

**Comment by willsower** [comment]
# seedingthermal.tex
## Notes:
- When it goes into the big math equations with the \hat, it's very hard to understand what's going on. (This is mostly mathmode, but it's very advanced mathmode)

## Tags Not Read:

**Comment by Wolrab** [comment]
> # Fennel.tex
> ## Notes:
> * It totally skipped most of \author??
> * Should we say abstract when \begin{abstract}
> * Mathmode here is awful, but they use mathmode for subscripts like `T$_v$` **FIXED NOW**
> 
> ## Tags Not Read:
> \journalname{}
> \offprints{}
> \institute{}

The T$_v$ issue is a very interesting problem since this is something I've frequently done in my own LaTeX documents, what was the solution you guys used to fix this?

**Comment by Wolrab** [comment]
# LanconMouhcine.tex
## Notes:
* When "$10^7 - 10^8$" is rendered, the first number is rendered as the super ugly "begin first parenthesis 10 to the power of 8 end first parenthesis" and the second one is rendered as "100 million." The same thing occurs in "$10^8 - 10^9$" elsewhere in the paper but with 10^8 read horrendously and 10^9 is read as "one billion" so my guess is minus is the key to this bug.
* \, is not account for (as TexSoup most likely doesn't parse it as a command) and is read out as "backslash (pause)". We should definitely try and figure out all the commands that TexSoup skips in this way since our default of ignoring unknown commands would otherwise handle all these whitespace commands.

## Tags Not Read:
* \title*{...}
* \toctitle{...}
* \titlerunning{...}
* \authorrunning{...}
* \institute{...}
	* All the above are commands to be rendered by \maketitle

**Comment by willsower** [comment]
> > # Fennel.tex
> > ## Notes:
> > 
> > * It totally skipped most of \author??
> > * Should we say abstract when \begin{abstract}
> > * Mathmode here is awful, but they use mathmode for subscripts like `T$_v$` **FIXED NOW**
> > 
> > ## Tags Not Read:
> > \journalname{}
> > \offprints{}
> > \institute{}
> 
> The T$_v$ issue is a very interesting problem since this is something I've frequently done in my own LaTeX documents, what was the solution you guys used to fix this?

Very temporary fix if anything. ANTLR doesn't recognize `$_v$` as mathmode. Even without ANTLR, a Sympy object could not just be `$_v$` either. -- Temporarily, i just made an if statement in `tex_to_sympy` to check if the first charachter is `_` or `^`. If so, process `underscore` or `to the power of`, skip mathmode and continue on.

Again to reiterate, this is a temporary solution since we can't have a full list of if/else. I saw other mathmode equations similiar to this, `$> 4$`, or `=3`, etc. But only did the ones for `_` and `^` since that was VERY common in these files.

**Comment by dylonrajah** [comment]
### wooten.tex

Notes:

- Has multiple authors and reads "by ..." before each authors name. Behaves as expected, may want to think about this. Works well
- Maybe a little too much break time on "s$^{-1}". Reads correctly
- Renderes "$30^o \pm 5^o$ as "30 to the power of O times pm times 5 to the power of o" (With parentheses)
- Issue with decimals and exponents. Reads "$5.7^o \pm 1.6^o$" as "57 to the O degree .... 16 to the O degree" similar to above
- When encountered "$9.5^o \pm 0.6^o$", said "Math could not be rendered". Looks to be the same format as the other \pm equations
- Paragraph starts were unclear

### Tags Not Read:

- \reference{}

**Comment by willsower** [comment]
# gameparadox-v7.tex
## Notes:
- 

## Tags Not Read:

**Comment by dylonrajah** [comment]
### stripes_4.tex

Notes:


### Tags Not Read:

**Comment by jrnemeth** [comment]
> ### stripes_4.tex
> Notes:
> 
> * Needs longer time before \cite
> * Says "dot" when sees a period at end of sentences. Only noticed this in the first two paragraphs
> * Read "$U/t \sim 4$" as "U times, begin first parentheses, begin second parentheses, t times begin 3 parentheses, sim times, end third parentheses, end second parentheses ,to power of -1 end first parentheses"
> * Had issues reading table. Said "Column 1, value" and didn't say the actual value of the column for many of the columns. Hard to visualize the table as its saying it.
> * Had troubles with \multicolumn{...}
> * Adds quite a bit of parentheses when no parentheses are in the equation
> * "$C_{i,j}$" --> "Math was not rendered"
> 
> ### Tags Not Read:
> * \title
> * \author
> * \address
> * \date
> * \begin{abstract}
> * \ref{...}
> * \mbox{...}
> * begin{....}
> * \caption{..}

seems like the main issue with the dot at the end of a sentence was following braces/brackets/parenthesis

I also see merit in adding the citations inline but saying them aloud does create a very messy interpretation of the reading.

**Comment by jrnemeth** [comment]
> # gameparadox-v7.tex
> ## Notes:
> * `\date` wasn't read out loud. (The contents were not read)
> * `\emph{stuff}` reads very slow (not sure if we want to change the emphasis a different way?)
> * I've brought this up before but when `\cite{stuff}.` returns as `cited by stuff dot`. The period after the command is read as `dot` literally.
> * `$(U^{a}, U^{b}, R^{a}, R^{b})$` did not render through math (probably because of the random commas)
> * Around 9 minutes and 20 seconds, when it reads these mathmodes, the begin parenthesis / end parenthesis gets really confusing. If I were listening to this without the paper in front of me, it would be gibberish (just because of the `begin third parenthesis , begin fourth parenthesis....etc`
> * Commands and mathmode do not render in tables
> * iff (is read as `if` but it means `if and only if`
> * Mathmode thinks `\in` is times
> * Reads `forall` instead as `for all`, reads like how this is sounded `forel` which could be confusing if the paper isn't infront of you
> * Huh...at line 100 in this paper there are nested itemize inisde of itemize commands
> 
> ## Tags Not Read:
> \begin{quote} \end{quote} **ADDED**
> \begin{thm} \end{thm} **ADDED**
> \begin{lem} \end{lem} **ADDED**
> \begin{proof} \end{proof} **ADDED**
> \begin{dfn} \end{dfn} **ADDED**
> \begin{prop} \end{prop} **ADDED**
> \begin{ex} \end{ex} **ADDED**
> \begin{tikzpicture} \end{tikzpicture} <- Is this a package?
> \begin{cor} \end{cor} **ADDED**
> 
> Listened to 30 minutes out of 1:48:42. The paper itself doesn't seem very long, however i think it takes a long time reading the mathmode

Tikzpicture is a graphical package that wouldn't be covered through speech conversion.

**Comment by WalkerJH** [comment]
# Conditions for Monopoles
* The beginning of the document contains the command `\smallfigwidth=3.4 in`. TexParser leaves `=3.4` and it is spoken by Polly.
* The sequence `M\'{o}l` within the `\author` command reads as "m backslash o l"
* Bold font text is pronounced very slowly. Sometimes it is almost impossible to understand
* This file would be a good demo of citations
* Period after \cite command is pronounced as "dot" -- this might be due to Polly and out of our control
* "et al" in the citations is within the `emph` command, and like bold it is pronounced way too slowly. Very difficult to understand
* Usage of command `Refs.~\onlinecite{Moller06,Moller09}` -- Polly just says "refs dot tilde". `Fig.~\ref{groundstates} (b)` works wonderfully however
* Decimals do not render in math mode. **FIXED**
* After my fix, `$h_{1}= 0.444a$` renders as "h one equals 0.444000000000000 times a" -- we may need to cut off extra zeros at the end of decimal numbers or get it to stop inserting them.
