### ISSUE TITLE
Repeating lines

### ISSUE THREAD

**Issue by willsower** [hutchresearch/latex2speech#76]
Using `sample.tex` this is in `Documentation/sample_issues/` directory in our project

The input at the top starting from line 40 is

`Some basic instructions are given next.
Put your text in here.  You can be a little sloppy    about
spacing.  It adjusts the text to look good.
{\small You can make the text smaller.}
{\tiny You can make the text tiny.}

Skip a line for a new paragraph.   
You can use italics ({\em e.g.} {\em  Thermodynamics is everywhere}) or {\bf bold}.
Greek letters are a snap: $\Psi$, $\psi$,
$\Phi$, $\phi$.  Equations within text are easy---`

However, it renders like this as the output for this section
```LaTeX
Some basic instructions are given next.
Put your text in here.  You can be a little sloppy    about
spacing.  It adjusts the text to look good.
  You can make the text smaller.  You can make the text tiny.
Skip a line for a new paragraph.
You can use italics ( <break time="40ms"/>
Some basic instructions are given next.
Put your text in here.  You can be a little sloppy    about
spacing.  It adjusts the text to look good.
  You can make the text smaller.  You can make the text tiny.
Skip a line for a new paragraph.
You can use italics ( <break time="40ms"/>
Some basic instructions are given next.
Put your text in here.  You can be a little sloppy    about
spacing.  It adjusts the text to look good.
  You can make the text smaller.  You can make the text tiny.
Skip a line for a new paragraph.
You can use italics ( <emphasis level="strong">  </emphasis>  e.g. <emphasis level="strong">  </emphasis>   Thermodynamics is everywhere ) or   bold .
Greek letters are a snap:  Psi  ,  psi  ,
 Phi  ,  phi  .  Equations within text are easy---
```

It repeats multiple times...

**Comment by Wolrab** [comment]
Recent changes/other bug fixes have made this bug not replicate. Closing until we find evidence of it again.
